### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Delt06** [Delt06/animation-texture-baking#1]
- [x] Baking and main pass
- [x] Shadow caster pass
- [x] DepthOnly and DepthNormals passes
- [x] desync animations
- [x] change to Mecanim
- [ ] write README:
  - [ ] Add image with draw calls
- [ ] animation blending
  - [ ] shader feature keyword for blending
